### ISSUE TITLE
validator error decoding CoreML model

### ISSUE THREAD

**Issue by egeola** [tf-coreml/tf-coreml#168]
Core ML model was successfully generated but I got this error: 

RuntimeError: Error compiling model: "Error reading protobuf spec. validator error: Load constant layer 'dropout_6/random_uniform:0' encodes a data buffer of length 0 but should be 1024.".

Also see the same error on Xcode.
<img width="778" alt="screen shot 2018-04-28 at 1 08 55 pm" src="https://user-images.githubusercontent.com/4679231/39399074-58bb555e-4ae5-11e8-92c0-06bbc911e0c5.png">

frozen.pb is attached.
Any suggestions?
Thanks

[frozen.pb.zip](https://github.com/tf-coreml/tf-coreml/files/1957945/frozen.pb.zip)

**Comment by aseemw** [comment]
The frozen graph, has two inputs: the vector of length 784 (the actual input) and another scalar (which is actually the "keep_prob" input meant for dropout during training). 

There are two things you can do:
- ideally, it would be best to remove the dropout portion and the corresponding input from the frozen graph and then convert. 
I am not entirely sure how to do that. There are couple of forums ([here](https://github.com/tensorflow/tensorflow/issues/5867), [here](https://github.com/tensorflow/tensorflow/issues/6124)) discussing this so that might be useful.

- you should be able to convert with the dropout sub-graph as well, although this wouldn't produce the most optimized CoreML graph. I tried converting using the following argument for input dict:
`input_name_shape_dict = {'Placeholder_25:0': (1, 784), 'Placeholder_27:0': (1,)}`
That seemed to work for me. I do not get any validator error. While evaluating the CoreML model make sure to give the value 1 for the second input.

**Comment by egeola** [comment]
Thanks @aseemw . I corrected the input dict with your suggestion and it worked.
