### ISSUE TITLE
placeholder for batch_norm gives error

### ISSUE THREAD

**Issue by dataplayer12** [tf-coreml/tf-coreml#258]
My network contains batch_norm layers and I am using a boolean placeholder for training flag. During conversion, this results in an error:

`AssertionError: train_flag:0 is a placeholder with incomplete shape <unknown>`

Is there a way to resolve this error without rewriting the network architecture without this flag?

**Comment by aseemw** [comment]
You are getting this error because:
- all placeholders are treated as inputs for the graph
- the converter needs to know the exact shapes of each placeholder, which is not available for this one

What if you just pass on the shape (1,) to the convert function (it does have an argument to take in input shapes)?

That might work, although the fact that you have the training graph, most likely means that there are other training related ops in the graph, which the converter will try to convert and most probably fail while doing so.
